modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/CodeOfArdonia/ResourceGenerator/issues"
license = "All Right Reserved"

[[mods]]
modId = "resource_generator"
version = "${version}"
displayName = "Resource Generator"
authors = "IAFEnvoy"
description = '''
A server side resource generator mod
'''
logoFile = "logo.png"

[[dependencies.resource_generator]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.resource_generator]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.2)"
ordering = "NONE"
side = "BOTH"
